plot(Power$datetime,Power$Sub_metering_1,type = "l",xlab = "",ylab = "Energy sub metering",)
lines(Power$datetime,Power$Sub_metering_2,col="Red")
lines(Power$datetime,Power$Sub_metering_3,col="Blue")
legend("topright",lty = 1,col = c("Black","Red","Blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
dev.copy(png,file="Plot3.png",height = 480, width = 480)
dev.off()